<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="EPPlus" Version="8.6.1" />
    <PackageReference Include="ExcelDataReader" Version="3.9.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.9.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CatalogSync.Application\CatalogSync.Application.csproj" />
    <ProjectReference Include="..\CatalogSync.Domain\CatalogSync.Domain.csproj" />
    <ProjectReference Include="..\CatalogSync.Persistence\CatalogSync.Persistence.csproj" />
  </ItemGroup>

</Project>
